### ISSUE TITLE
fel asciinema länk, linux kmom05 mazerunner loop

### ISSUE THREAD

**Issue by pejg12** [dbwebb-se/website#10]
I kraven för uppgiften att skapa mazerunner ska det finnas två asciinemas som visar hur det färdiga resultatet förväntas vara, men artikeln visar den första filmen två gånger istället för två olika filmer.

Jag skulle ha fixat problemet själv om jag bara visste hur man hittade rätt "src" så att det passar in i den nuvarande koden...

Källkoden: [./mazerunner loop](https://github.com/dbwebb-se/website/blob/master/content/uppgift/201_los-mazen-med-din-mazerunner-i-bash.md)
`[ASCIINEMA src=1voz3ecbgsbu5dytp9sz5n2kb]` (rad 148)
Borde länka till: https://asciinema.org/a/23368

**Comment by mosbth** [comment]
https://dbwebb.se/uppgift/los-mazen-med-din-mazerunner-i-bash

Lagade i b9a2593de5484f38fef1c16cb5c803a57ab2ad75
