### ISSUE TITLE
Dead link (404) on first page

### ISSUE THREAD

**Issue by j-lindb73** [dbwebb-se/website#100]
File to edit:
https://github.com/dbwebb-se/website/blob/master/content/kurser/block-kurser.md

"genvägar till kursmaterial och kursmoment" links to https://dbwebb.se/:///home/mos/htdocs/dbwebb.se/script/kurser.

Should probably be linking to "https://dbwebb.se/kurser". 
The same goes for the block headline (404).

**Comment by mosbth** [comment]
Jao, det är en glitch i min process som värmer upp cachen när en ny version av webbplatsen publiceras.

Jag hårdkodade de två länkarna nu så att det bör fungera (samt två länkar till bilder som led av samma bekymmer).
