### ISSUE TITLE
Stavfel Databaskurs

### ISSUE THREAD

**Issue by Elmittil** [dbwebb-se/website#102]
https://github.com/dbwebb-se/website/blob/master/content/guide/kom-igang-med-sql-i-mysql/130_skapa-en-databas.md

<img width="1026" alt="Screenshot 2021-01-21 at 10 56 32" src="https://user-images.githubusercontent.com/73843551/105335595-83f70680-5bd8-11eb-843a-ef7df645a50b.png">

**Comment by mosbth** [comment]
Fixat. Tacksam.
