### ISSUE TITLE
python kmom06: problem med symbolisk länk i cygwin

### ISSUE THREAD

**Issue by pejg12** [dbwebb-se/website#11]
https://dbwebb.se/kunskap/anvand-externa-moduler-i-python-for-att-hamta-information-pa-webben#cli

Uppgiften är att kunna köra kommandot `mynameis` istället för `./mynameis.py` men det fungerar inte som tänkt i Cygwin eftersom `ln -s mynameis.py mynameis` ändå inte gör `./mynameis` (utan filändelse) körbar.

På [Stackoverflow finns lösningen](http://stackoverflow.com/a/18659632/2148504) att skriva `export CYGWIN="winsymlinks:nativestrict"` för att få rätt sorts symboliska länkar, men jag kan inte testa det i min miljö\* för att se om det fungerar.

_\* Windows 10 i en VirtualBox med filerna i en Shared Folder... `cmd` hävdar "The device does not support symbolic links". Om jag gör den symboliska länken i linux så fungerar resten av guiden i min virtuella Windows, men har man en riktig Windows kan man ju inte göra så._

**Comment by mosbth** [comment]
Jag kan skapa symlänk i cygwin och på det sättet få filen körbar, så som det beskrivs i exemplet. 

Men, tittar jag på exempelkoden i kursrepot så borde mynameis och mynameis2 vara symlänkar, det är de på unixlmaskiner men inte i cygwin då de istället blir konverterade till en textfil.
http://stackoverflow.com/questions/5917249/git-symlinks-in-windows

Summa summarum så funkar inte symlänkar, via git, så bra i detta fallet. Jag tror att felet kan finnas på fler platser. har ingen bra plan för hur jag skall lösa det för stunden. Låter som jag behöver ändra i kursrepot (bort med symlänkar) och redigera eventuella artiklar.

**Comment by pejg12** [comment]
Mer info om symboliska länkar i Cygwin: https://dbwebb.se/f/48222

Jag har inte testat om den lösningen fungerar för uppgiften mynameis än, återkommer.

**Comment by pejg12** [comment]
Har testat lite fler varianter nu, men lyckas ändå inte skapa symboliska länkar i min virtuella miljö så jag kan nog inte hjälpa till med att lösa den här buggen från vanliga studenters perspektiv.

Låter annars som en bra strategi att försöka undvika symlänkar. Och sen kanske lägga ett sånt moment i linuxkursen istället ;)

**Comment by mosbth** [comment]
Försöker undvika symboliska länkar.
