### ISSUE TITLE
Klona jsramverk

### ISSUE THREAD

**Issue by gmiak** [dbwebb-se/website#124]
Hey! Jag får ett felmeddelande när jag kör _**dbwebb clone jsramverk**_

![jsramverk](https://user-images.githubusercontent.com/24249352/187096729-97529cf8-ebe5-4635-a257-5c1119e73f20.png)

**Comment by emilfolino** [comment]
Det finns inget kursrepo kopplat till dbwebb-cli. Se istället: https://jsramverk.se/#repo

**Comment by emilfolino** [comment]
Det finns inget kursrepo kopplat till dbwebb-cli. Se istället: https://jsramverk.se/#repo
