### ISSUE TITLE
[Error] in article: Sårbarhetsanalys - Del 2 | dbwebb

### ISSUE THREAD

**Issue by Miyarima** [dbwebb-se/website#147]
### Link to the error

https://dbwebb.se/uppgift/sarbarhetsanalys-del2#testfall

### Describe what the error is?

Borde stå 10 testfall här :) (tror jag)

### The marked text

```bash
Minimum 9 testfall totalt. Försök att testa olika delar av appen!
```

**Comment by epkmagr** [comment]
Uodated to 9
