### ISSUE TITLE
Update article about travis/scrutinizer with whitelist part

### ISSUE THREAD

**Issue by thulin82** [dbwebb-se/website#15]
Det verkar som att travis kräver whitelist numera för att generera code coverage, detta bör tas upp här:
https://dbwebb.se/kunskap/lat-travis-ci-och-scrutinizer-hjalpa-dig-med-att-testa-din-kod

Fixar det själv när jag får tid, men nu finns det en issue på det i alla fall.
Forumtråd: https://dbwebb.se/forum/viewtopic.php?f=40&t=5774

**Comment by thulin82** [comment]
Verkar likna statistiskt säkerställt att whitelist löser problemen folk har, 3/3 as we speak :-)

**Comment by mosbth** [comment]
Jup, känns som jag behöver göra en allmän översyn av artikeln. Vill minnas att den var uppbyggd av taggar som gör det lite bökigt att uppdatera kodexemplet, utan att göra det från början till slut.

Antar att jag även bör lösa "problemet" i den artikel som introducerar code coverage.
https://dbwebb.se/kunskap/borja-att-skriva-testfall-med-phpunit-for-din-php-kod#coverage

**Comment by thulin82** [comment]
Fortf aktuellt, eller stänga? @mosbth
