### ISSUE TITLE
Bad link leads to 404

### ISSUE THREAD

**Issue by pejg12** [dbwebb-se/website#2]
Article: http://dbwebb.se/uppgift/ett-terminal-baserat-spel-i-python-steg2
Line: 90 (in the HTML)
Link location in the text: 
> Du har gjort **första övningen med Python och curses**.

Bad link:
http://dbwebb.se/ett-terminal-baserat-spel-i-python-steg1

Change to this instead:
http://dbwebb.se/uppgift/ett-terminal-baserat-spel-i-python-steg1

**Comment by mosbth** [comment]
Updated.
