### ISSUE TITLE
Blå rutor som ingen läser

### ISSUE THREAD

**Issue by pejg12** [dbwebb-se/website#3]
Viktig information läggs för tillfället i blå rutor, men pga designen är det ingen som läser de blå rutorna.

Ett förslag är att inte omsluta rutorna med en border. Om de smälter in bättre i brödtexten är det större sannolikhet att de uppmärksammas. Kanske kan de skiljas från brödtexten med bara border-left och margin-left. Eller bara en rubrik. Eller kanske med en varningssymbol. Kanske är det bättre att välja en varningsfärg som röd istället för diskret blå.

Informationen i de blå rutorna kan också i vissa fall flyttas till en bättre plats i texten. Exempelvis handlar den blå rutan högst upp i http://dbwebb.se/kunskap/labbmiljo-for-javascript-i-webblasaren om att den här artikeln kanske inte borde läsas över huvud taget. Sådan information borde presenteras allra högst upp i artikeln, likt Wikipedias hänvisning till relaterade artiklar (som "För andra betydelser, se ..." https://sv.wikipedia.org/wiki/Bamse )

**Comment by mosbth** [comment]
Skall tänka på det nu när artiklarna konverteras till den nya webbplatsen.

Rimligt att lägga hänvisning till nyare artikel överst/högt upp i introduktionen.

**Comment by thulin82** [comment]
Ser rätt bra ut nu i "nya" strukturen?

![labbmiljo for javascript i webblasaren _ dbwebb](https://cloud.githubusercontent.com/assets/526141/18345823/674dc48e-75bd-11e6-8c19-0a2026f93d7a.png)

**Comment by pejg12** [comment]
Det enda som skiljer är att det nu är en info-symbol uppe i hörnet. Men det kanske är allt som behövs. Får se hur många som missar information i höst.

För övrigt gillar jag skarpt de nya gula rutorna:
https://dbwebb.se/kunskap/installera-unix-terminalen-cygwin-pa-windows#install-apt-cyg
![gulruta](https://cloud.githubusercontent.com/assets/2937580/18380672/be2c154c-7678-11e6-874b-ec5e3055dc48.png)

**Comment by mosbth** [comment]
Mm, har börjat använda lite mer gula rutor, när de är "varningar", antar att de kan vara svårare att ducka än de mer "snälla" blåa rutorna.

Än finns inte stöd för röda rutor, men det kanske behövs. Tex för artiklar som passerat sitt bäst före datum.

**Comment by pejg12** [comment]
Jag tror att det här problemet är löst. Jag har i alla fall inte upplevt att jag har behövt peka på några inforutor alls sedan den här uppdateringen.

**Comment by mosbth** [comment]
Vi stänger tills vidare.
