### ISSUE TITLE
Korrekturläst webapp-v2

### ISSUE THREAD

**Issue by pejg12** [dbwebb-se/website#42]
Det finns många återkommande skrivproblem i den nyskapade kursen **webapp-v2**. Istället för att bara rätta felen i smyg så har jag här sammanställt de problem jag har hittat, för att på så sätt försöka undvika samma problem i framtida artiklar. Jag planerar att rätta nedanstående problem själv under sommaren (2017).

För att hitta de återkommande skrivfelen har jag läst igenom relevanta artiklar i `content/kurser/webapp-v2/` och `content/uppgift/`. Det finns även många relevanta artiklar i `content/kunskap/` men jag tror inte att det finns så många nya skrivfel där. Genom att använda sig av nedan tabeller och `grep` så kan man nog rätta till det mesta även i kunskapsartiklarna utan att lusläsa dem.

## Versaler och gemener
Jag har besökt varje projekts webbsida och tagit reda på hur de själva väljer att skriva sitt varumärke.

Nuvarande | Förslag
--------- | -------
Dbwebb | dbwebb
mithril | Mithril
cordova | Cordova
android | Android
Github | GitHub

## Förkortningar och grammatiska skiljetecken

När jag korrekturläste artiklar skrivna för webapp-v2 upptäckte jag att vissa saker skrevs väldigt inkonsekvent, till exempel API och api. För att kunna välja en gemensam lösning sökte jag råd bland [TT:s skrivregler](https://tt.se/tt-spraket/skriv/forkortningar/).

> En del förkortningar har med tiden blivit självständiga ord i svenskan och dessa skriver vi gement: cd, cd-rom, id-kort, pc, pm, sms, tv.

> I några fall är små bokstäver att föredra därför att besläktade ord brukar skrivas gement. Det gäller särskilt tekniska termer: adsl, dab-radio, dvd, md (mini disc), gps, gprs, mms, mp3, sim-kort, vhs, wap. Dock skriver vi IT och 3G med versaler.

> När en förkortning ingår i sammansatt ord sätts vanligen bindestreck mellan leden: IT-kommission, mc-polis, digital-tv-box. Om förkortningen inte läses bokstav för bokstav utan som ett vanligt ord kan man ofta slopa bindestrecket: Natostyrka, Ikeasoffa.

> Bestämd form av initialförkortning skrivs med kolon före ändelsen: tv:n, vd:n. Samma sak gäller vid genitivändelse till förkortningar som uttalas bokstav för bokstav: FN:s, USA:s, SKF:s. Till förkortningar som uttalas som ord fogas genitivändelsen utan kolon: Natos, Sidas.

Nuvarande | Förslag
--------- | -------
API't | api:t
api't | api:t
API'er | api:er
API:er | api:er
api'er | api:er
REM api:t | REM-api:t
REM api't | REM-api:t
JSON API'er | JSON-api:er
json api | JSON-api
JSON fil | JSON-fil
JSON filer | JSON-filer
JSON data | JSON-data
github repo | GitHub-repo
github vy | GitHub-vy
Github api't | GitHub-api:t
plugin:et | pluginet
browser:n | browsern

## Särskrivning
Vissa ord sätts samman med bindestreck, andra sätts bara ihop rakt av, och vissa sätts ihop genom att ta bort eller förändra bokstäver. Här har jag bara gått efter känsla och ändrat till det som "känns rätt" enligt min erfarenhet.

Nuvarande | Förslag
--------- | -------
javascript ramverket | javascript-ramverket
API dokumentationen | api-dokumentationen
`GET` anrop | `GET`-anrop
HTTP anrop | HTTP-anrop
android emulator | Android-emulator
cordova appen | Cordova-appen
HTTP requesten | HTTP-requesten
hybrid appar | hybridappar
desktop miljöer | desktopmiljöer
Nobel app | Nobelapp
Nobel festen | Nobelfesten
års vy | årsvy
mithril komponenter | Mithrilkomponenter
mithril funktionen | mithrilfunktionen
grid system | gridsystem
cordova projekt | Cordovaprojekt
mithril projekt | Mithrilprojekt
Gomoku server | Gomokuserver
Gomoku klient | Gomokuklient
vinkällare app | vinkällarapp
värd dator | värddator
Android appar | Androidappar
android emulatorn | Androidemulatorn
system variabeln | systemvariabeln
design val | designval
meapp | me-app

## Tryckfel och stavfel
På några få ställen hittade jag vanliga tryckfel. Jag hittade även direkta grammatiska fel, såsom valet mellan en/ett.

Nuvarande | Förslag
--------- | -------
jobabr | jobbar
Ett mobilanpassad | Ett mobilanpassat
mobilanpassad formulär | mobilanpassat formulär
dashboardet | dashboarden
ditt dashboard | din dashboard
använderen | användaren
användar | använder
autensiera | autentisera
5 stycken widgets | fem (5) widgets
pluginen | pluginet
ett cheatsheets om | ett cheatsheet som
LEGO byggsätt samling | LEGO-byggsetsamling
CRUD-functions | CRUD-funktioner
även hittar med info | även hitta mer info

**Comment by pejg12** [comment]
Jag är inte helt säker på hur det blir bäst med commits och pull requests. Såhär tänkte jag lösa det:

1 commit ändrar cordova till Cordova i ca 15 filer.
1 commit ändrar mithril till Mithril i ca 20 filer.
1 commit ändrar olika varianter av API't till api:t i ca 40 filer.
...
1 pull request sammanställer ca 40 commits som gör ändringar i ca 50 filer.

För kontrollering hade det säkert varit lättast att bara läsa igenom en fil i taget, men eftersom jag ändrar samma problem i många filer samtidigt är det troligtvis mer önskvärt att kunna säga "den där specifika ändringen vill vi inte genomföra i någon fil, men alla andra ändringar ser bra ut".

Låter det bra? Ska jag köra på?

**Comment by mosbth** [comment]
Jag är inte sugen på sed replace i ett större antal artiklar utan att samtidigt gå igenom dem tillsammans med den som skrivit dem. En sed replace är också en potentiell felkälla som kan införa nya fel.

Även om sed replace "löser" visa felstavningar så prioriterar jag att långsamt förbättra de artiklar som är skrivna och kanske mer de nya artiklar som skrivs.

Det finns en viss vinst i att göra som du föreslår med sed replace. Men jag prioriterar att använda underlaget du gjort som utbildningsmaterial inför skrivande av nya artiklar och gneomgång av äldre artiklar.

Ibland när man skriver texter så märker jag också att det är lättare att omformulera en mening/stycke än att försöka få in ett visst ord, orden blir enklare vid en omformulerad medning. Kanske är det inte bara vissa ord som behöver förbättras utan även formulering/meningsbyggnad.

Något som kan vara viktigt i längden är att köra spellchecker som ett valideringsverktyg på artiklar. Det kräver spellchecker i Atom och som ett extern valideringsverktyg samt en god ordlista som start och en möjlighet att bygga ut den ordlistan.

Så, hellre omforma deta till utbidningsmaterial, med referens till svenskt språkbruk (referens som säger hur man skriver vissa ord/stycken) samt autmatisk stavningskontroll i Atom (foruminlägg/artikel som visar hur man kommer igång) och incheckad ordlista samt ett externt valideringsverktyg som kollar stavning (och eventuellt längre ordkonstruktioner).
