### ISSUE TITLE
Pythonlabbarna säger att det både finns och inte finns extrauppgifter

### ISSUE THREAD

**Issue by pejg12** [dbwebb-se/website#46]
Precis ovanför kraven står det:
> `Sedan finns extra uppgifter du kan utföra om du så väljer. [Varför skall jag göra extrauppgiftena](kurser/faq/varfor-gora-extra-uppgifter)?`

Sen, under sin egen rubrik, står det:
> `Extrauppgift {#extra}`
> `-----------------------`
> 
> `Det finns ingen extra uppgift.`

Jag skulle kunna flytta texten precis som den är, men jag tycker den borde formuleras annorlunda när den ligger under en helt egen rubrik istället.

Det gäller uppgifterna:
* 1081_python-med-varden-och-variabler.md
* 136_python-med-villkor-och-loopar.md
* 140_python-med-funktioner.md
* 1082_python-listor.md
* 138_python-med-dictionaries-och-tupler.md

**Comment by mosbth** [comment]
Möjligen finns samma struktur i htmlphp-kursens motsvarande labbeskrivningar.
