### ISSUE TITLE
Gravatar bilder

### ISSUE THREAD

**Issue by ocpu** [dbwebb-se/website#50]
Ja. Gravatar bild som profil bild?
T.ex som denna link som är en valid bild länk https://www.gravatar.com/avatar/25bc3ab2d99228888fe62ee99f21aa41 får fel medelandet "URL:en du angav är felaktig."

**Comment by mosbth** [comment]
Sammanhanget är profilbild i forumet.
Lägg till ändelsen `.jpg` så fungerar det.

**Comment by ocpu** [comment]
Jag lade till `.png` och det funkade.
