### ISSUE TITLE
Olika kursmapp sökvägar?

### ISSUE THREAD

**Issue by ocpu** [dbwebb-se/website#60]
I instruktionerna till uppgifterna kopierar vi från tidagre moment och från _example_. Finns det någon anledning varför vissa kommandon ska utföras i _me_ mappen och andra i _kursmappen_? Bara lite fundersam.

**Comment by mosbth** [comment]
Finns ingen direkt anledning. Det handlar nog mest om den som skriver uppgiften och hur den tycker det enklaste/kortaste copy-kommandot blir.
