### ISSUE TITLE
Fel tabell visas upp i "Kom igång med SQL"/"Lägg till rader"

### ISSUE THREAD

**Issue by litemerafrukt** [dbwebb-se/website#62]
I dokumentet [Lägg till rader](https://github.com/dbwebb-se/website/blob/master/content/guide/kom-igang-med-sql-i-mysql/150_lagg-till-rader.md) i "Kom igång med SQL" visas det en tabell i slutet med felaktiga löner jämfört med de man får om man följer artikeltexten.

**Comment by mosbth** [comment]
Ajdå.
