### ISSUE TITLE
Gravatar är http istället för https

### ISSUE THREAD

**Issue by pejg12** [dbwebb-se/website#7]
När jag är inne på dbwebb.se/forum finns min gravatar uppe i hörnet, men den går över http istället för http**s** så jag får en konstant varning om att sidan bara är partially encrypted.

Jag provade att lägga till ett s i adressen och den funkar fortfarande, så det borde vara lätt att uppdatera om jag bara kunde hitta forumkoden...

Exempelfil som fungerar med https:
https://www.gravatar.com/avatar/f902f74bd5a291d33ba4eac7845b52dc?r=pg&s=40&d=wavatar

**Comment by pejg12** [comment]
Hm, jag gick in för att ändra min till https och det gjorde ingen skillnad. Min profil "uppdateras", men bilden fortsätter skickas över http.

**Comment by thulin82** [comment]
Gravatar-filerna verkar ligga (och nu kollade jag i min egen installation av phpBB, så results may vary) under phpbb/avatar/driver/
Men jag har svårt att leta vidare då jag inte vet om det är default-phpBB som gäller, eller dbwebb använder någon extension, och jag inte heller har koll på version.

**Comment by pejg12** [comment]
Den gravatar som visas uppe i hörnet på forumet har tydligen ingenting med forumets visningsbild att göra.

Forumets kod finns inte tillgängligt publikt, men gravatar-koden kommer från från Anax:
https://github.com/mosbth/anax/blob/master/view/default/profile-phpbb.tpl.php
Koden i Anax borde fungera, men troligtvis använder forumet en äldre variant av koden.

**Comment by mosbth** [comment]
Temat i phpbb som styr detta har följande kod:

```php
    <span class="profile-phpbb">
        <!-- IF S_USER_LOGGED_IN -->
        <span class="gravatar">
            <a href="/forum/ucp.php">
                <img src="{U_GRAVATAR}?r=pg&amp;s=40&amp;d=wavatar" alt="">
            </a>
        </span>
        <!-- ELSE -->

        <span class="login">
            <a href="/forum/ucp.php?mode=login">
                <span class="text">Login</span>
                <i class="icon fa fa-sign-in"></i>
            </a>
        </span>
        <!-- ENDIF -->

    </span>
```

Så `U_GRAVATAR` styrs av forumet. Fältet är tillagt i användarens profil. Man får ta ett steg in i phpbb för att se vad som händer.

Men även om man löser detta, så är det fortfarande ett problem att alla bilder som användare lagt till i forumtrådar kan vara http och inte https. Så lösningen att säkra https för alla delarna i ett forum, är ett större projekt som innefattar alla delar som en användare kan länka till.

**Comment by mosbth** [comment]
Oj, klickade fel knapp.

**Comment by pejg12** [comment]
Det känns rimligt att få en varning när användare har länkat bilder som inte är https, men det känns inte lika rimligt att få en varning för alla sidvisningar på de andra delarna av forumet.

Hoppas @thulin82 hittar `U_GRAVATAR` i sin phpbb-installation.

**Comment by thulin82** [comment]
Är det standardtema i phpbb, @mosbth ? Och vilken version av phpbb?

Håller med @pejg12 , löser vi gravatar-problemet är det nog ett bra första steg, vad folk länkar för bilder är svårt att göra något åt....

**Comment by mosbth** [comment]
Versionen är 3.0.9 och temat är troligen baserat på ett standardtema som utvecklats och sedan modifierats av mig. Det känns som hanteringen av U_GRAVATAR ligger i phpbb, oavsett tema (peppar).
