### ISSUE TITLE
Försvunnen fil i [Koppla upp sig mot en databas] instruktion

### ISSUE THREAD

**Issue by scarsam** [dbwebb-se/website#73]
Försökte tanka hem filen som var länkad här, men den kan inte hittas.:
`wget -O jetty.sqlite https://github.com/mosbth/htmlphp/blob/master/example/sqlite/jetty.sqlite?raw=true` 

Länk till README: https://github.com/dbwebb-se/website/blob/master/content/kunskap/206_en-kommandoradsklient-for-sqlite.md

Tog mig ett tag att inse att filen som laddades ner var tom, och försökte att ladda ner den från Github och insåg då att den inte existerade.

**Comment by mosbth** [comment]
Fint du sa till, filen har ändrat namn till boatclub.sqlite. Jag uppdaterade artikeln.
