### ISSUE TITLE
FOEM - Frequently Occurring Error Messages

### ISSUE THREAD

**Issue by emilfolino** [dbwebb-se/website#74]
Skapa ett dokument med möjlighet för att söka antingen Ctrl-f eller via ett sökfält med filtrering.

Tanken är felmeddelande -> lösning.

Exempel:

### FAILED Not a valid combination #{länkning}

`BTHMAC0169:python efo$ dbwebb create lab1
find: me: No such file or directory
FAILED Not a valid combination of 'python' and 'lab1'.`

Kontrollera först att du har stavat rätt på labben eller examinationen du försöker skapa.

Om du har stavat rätt är det för att katalogen som labben eller examinationen ska skapas i inte finns. Detta kan åtgärdas med `dbwebb init`

### Simplifiable if-statement
Då du har en return i förstadelen av din if-sats kan detta förenklas från:

`
if something:
    return "42"
else:
    return "27"
` 
till

`
if something:
    return "42"

return "27"
`

**Comment by mosbth** [comment]
Delvis, för pylint, finns en grund i kursrepot under (iallafall relaterat i viss mån):
https://github.com/dbwebb-se/python/blob/master/example/pylint/messages.md

**Comment by mosbth** [comment]
När det gäller dbwebb-cli så borde det kunna bli bättre felmeddelanden som är tydliga, eventuellt på svenska, Man kan göra mer tester och kontroller som gör felmeddelandena mer "självförklarande". Det finns ju en begränsad omfattning av de vanligaste felen som uppkommer.
Troligen något att tänka på lite extra i nya dbwebb-cli.

**Comment by emilfolino** [comment]
Tänkte främst att man hade en samlat plats för alla felmeddelanden som uppstår. Tror många gånger att studenter, främst under första året inte vet vilket verktyg det är kopplat till. Men kanske blir för stort ett dokument.
